<!doctype html>
    <html ng-app="project">
      <head>
        <script src="/js/angular.min.js"></script>
        <script src="/js/angular-route.min.js"></script>
        <script src="/js/angular-resource.js"></script>
        
        <link rel="stylesheet" href="/css/bootstrap-responsive.min.css">
        <link rel="stylesheet" href="/css/bootstrap.min.css">

        <script src="/js/company/project.js"></script>
        
      </head>
      <body>
        <h2>Some Projects</h2>
        <div ng-view></div>
      </body>
    </html>